<?php

namespace App\Console\Commands;

use App\Services\WaybillExportService;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Storage;

class PruneWaybills extends Command
{
    protected $signature   = 'waybills:prune {--days=7 : Delete stored waybill PDFs older than this many days}';
    protected $description = 'Delete waybill PDFs generated by the API that are older than the given number of days';

    public function handle(): int
    {
        $disk    = Storage::disk('public');
        $cutoff  = now()->subDays((int) $this->option('days'))->getTimestamp();
        $deleted = 0;

        foreach ($disk->allFiles(WaybillExportService::STORAGE_DIR) as $file) {
            if ($disk->lastModified($file) < $cutoff) {
                $disk->delete($file);
                $deleted++;
            }
        }

        // Remove the now-empty per-file and per-day folders
        foreach (array_reverse($disk->allDirectories(WaybillExportService::STORAGE_DIR)) as $dir) {
            if (empty($disk->allFiles($dir))) {
                $disk->deleteDirectory($dir);
            }
        }

        $this->info("Deleted {$deleted} waybill file(s).");

        return self::SUCCESS;
    }
}
